import Head from 'next/head'
import Header from '../components/header'
import Nav from '../components/Nav'

//IMPORTANT after creating this hulu page copy this repo and modify the copied one for my portfolio

export default function Home() {
  return (
    <div>
      {/* head tag is the props for the actual tab for the website in the browser */}
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        {/* FYI tailwind remove h1 h2 h3 so on sizes aka headless ui  */}
      {/* header */}

   

      <Header/>

       {/* nav */}
       <Nav/>
      {/* results */}

    </div>
  )
}
