import Head from 'next/head'
import Header from '../components/header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'

//IMPORTANT after creating this hulu page copy this repo and modify the copied one for my portfolio

export default function Home({ results }) {
  return (
    <div>
      {/* head tag is the props for the actual tab for the website in the browser */}
      <Head>
        <title>Hulu 2.0</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* FYI tailwind remove h1 h2 h3 so on sizes aka headless ui  */}
      {/* header */}

      <Header />

      {/* nav */}
      <Nav />
      {/* results */}
      <Results results={results} />
    </div>
  )
}
//render for server side (based for each page)
export async function getServerSideProps(context) {
  const genre = context.query.genre

  //next page set the request to the database for the movies/tv
  const request = await fetch(
    `https://api.themoviedb.org/3/${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json())

  return {
    props: {
      results: request.results,
    },
  }
}
